/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedTalksNewRouteImport } from './routes/_authenticated/talks.new'
import { Route as AuthenticatedTalksTalkIdRouteImport } from './routes/_authenticated/talks.$talkId'
import { Route as AuthenticatedLayoutTalksRouteImport } from './routes/_authenticated/_layout.talks'
import { Route as AuthenticatedLayoutHomeRouteImport } from './routes/_authenticated/_layout.home'
import { Route as AuthenticatedLayoutFavoritesRouteImport } from './routes/_authenticated/_layout.favorites'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTalksNewRoute = AuthenticatedTalksNewRouteImport.update({
  id: '/talks/new',
  path: '/talks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTalksTalkIdRoute =
  AuthenticatedTalksTalkIdRouteImport.update({
    id: '/talks/$talkId',
    path: '/talks/$talkId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLayoutTalksRoute =
  AuthenticatedLayoutTalksRouteImport.update({
    id: '/talks',
    path: '/talks',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutHomeRoute = AuthenticatedLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedLayoutFavoritesRoute =
  AuthenticatedLayoutFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/favorites': typeof AuthenticatedLayoutFavoritesRoute
  '/home': typeof AuthenticatedLayoutHomeRoute
  '/talks': typeof AuthenticatedLayoutTalksRoute
  '/talks/$talkId': typeof AuthenticatedTalksTalkIdRoute
  '/talks/new': typeof AuthenticatedTalksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/favorites': typeof AuthenticatedLayoutFavoritesRoute
  '/home': typeof AuthenticatedLayoutHomeRoute
  '/talks': typeof AuthenticatedLayoutTalksRoute
  '/talks/$talkId': typeof AuthenticatedTalksTalkIdRoute
  '/talks/new': typeof AuthenticatedTalksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/favorites': typeof AuthenticatedLayoutFavoritesRoute
  '/_authenticated/_layout/home': typeof AuthenticatedLayoutHomeRoute
  '/_authenticated/_layout/talks': typeof AuthenticatedLayoutTalksRoute
  '/_authenticated/talks/$talkId': typeof AuthenticatedTalksTalkIdRoute
  '/_authenticated/talks/new': typeof AuthenticatedTalksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/favorites'
    | '/home'
    | '/talks'
    | '/talks/$talkId'
    | '/talks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/favorites'
    | '/home'
    | '/talks'
    | '/talks/$talkId'
    | '/talks/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/favorites'
    | '/_authenticated/_layout/home'
    | '/_authenticated/_layout/talks'
    | '/_authenticated/talks/$talkId'
    | '/_authenticated/talks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/talks/new': {
      id: '/_authenticated/talks/new'
      path: '/talks/new'
      fullPath: '/talks/new'
      preLoaderRoute: typeof AuthenticatedTalksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/talks/$talkId': {
      id: '/_authenticated/talks/$talkId'
      path: '/talks/$talkId'
      fullPath: '/talks/$talkId'
      preLoaderRoute: typeof AuthenticatedTalksTalkIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout/talks': {
      id: '/_authenticated/_layout/talks'
      path: '/talks'
      fullPath: '/talks'
      preLoaderRoute: typeof AuthenticatedLayoutTalksRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/home': {
      id: '/_authenticated/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedLayoutHomeRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/favorites': {
      id: '/_authenticated/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedLayoutFavoritesRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutFavoritesRoute: typeof AuthenticatedLayoutFavoritesRoute
  AuthenticatedLayoutHomeRoute: typeof AuthenticatedLayoutHomeRoute
  AuthenticatedLayoutTalksRoute: typeof AuthenticatedLayoutTalksRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutFavoritesRoute: AuthenticatedLayoutFavoritesRoute,
  AuthenticatedLayoutHomeRoute: AuthenticatedLayoutHomeRoute,
  AuthenticatedLayoutTalksRoute: AuthenticatedLayoutTalksRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthenticatedTalksTalkIdRoute: typeof AuthenticatedTalksTalkIdRoute
  AuthenticatedTalksNewRoute: typeof AuthenticatedTalksNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthenticatedTalksTalkIdRoute: AuthenticatedTalksTalkIdRoute,
  AuthenticatedTalksNewRoute: AuthenticatedTalksNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
